---
token: YOUR_TOKEN
version: 0.1.0
serverid.welcome: |
    YOUR WELCOME MESSAGE HERE
serverid.welcome-mobile: |
    MOBILE FRIENDLY WELCOME MESSAGE
max-poll-time: 180
dice:
    max-dice: 10
    max-sides: 100
sound:
    enabled: false
    sound-folder: sounds
    servers:
        serverid:
            channel: channelID
            volume: 1.0